# Operaciones fundamentales de vectores y matrices

## Vectores

In [2]:
import numpy as np
# Crear un vector de numpy
vector_u = np.array([10, 20, 30, 40])
vector_v = np.array([1,2,3,4])
# Suma de vectores
vector_suma= vector_u + vector_v
# Producto escalar
escalar = 5
vector_pescalar = escalar*vector_u
# Producto punto
vector_ppunto = vector_u @ vector_v

print("Suma de vectores: ", vector_suma,"\nProducto escalar: ", vector_pescalar, "\nProducto punto: ", vector_ppunto)

Suma de vectores:  [11 22 33 44] 
Producto escalar:  [ 50 100 150 200] 
Producto punto:  300


## Matrices

In [3]:
import numpy as np
# Crear una matriz de numpy
A = np.array([
[1, 2],
[3,4]])
B=np.array([
[-3,4],
[5,6]])
# Suma de matrices
C=A+B
# Producto escalar
escalar = 5
D = escalar*A
# Producto entre matrices
E= np.dot(A,B)
print("Suma de matrices:\n ", C,"\nProducto escalar:\n ", D, "\nProducto entre matrices:\n ", E)


Suma de matrices:
  [[-2  6]
 [ 8 10]] 
Producto escalar:
  [[ 5 10]
 [15 20]] 
Producto entre matrices:
  [[ 7 16]
 [11 36]]
